from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),  # Main page
    path('register/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('profile1/', views.profile_view, name='profile1'),
    path('block_user/<int:reg_id>/', views.block_user, name='block_user'),
    path('unblock_user/<int:reg_id>/', views.unblock_user, name='unblock_user'),
    path('profile/', views.profile, name='profile'),
    path('edit_personal_details/', views.edit_personal_details, name='edit_personal_details'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('edit-profile/<int:reg_id>/', views.edit_profile, name='edit_profile'),
    path('education/', views.education, name='education'),
    path('edit_education/', views.edit_education, name='edit_education'),
    path('family/', views.family, name='family'),
    path('edit_family/', views.edit_family, name='edit_family'),
    path('profile1/<int:reg_id>/', views.profile_view, name='profile1'),  # Ensure this line exists
    path('upload-images/<int:reg_id>/', views.upload_images, name='upload_images'),
    path('view_all_details/<int:personal_id>/', views.view_all_details, name='view_all_details'),
    path('view_profile/<int:personal_id>/', views.view_profile1, name='view_profile1'),
    path('download_profile_pdf/<int:personal_id>/', views.download_profile_pdf, name='download_profile_pdf'),
    path('upload_more_image/', views.upload_more_image, name='upload_more_image'),
    path('packages/create/', views.package_create, name='package_create'),
    path('packages/', views.view_packages, name='view_packages'),
    path('packages/edit/<int:package_id>/', views.edit_package, name='edit_package'),
    path('packages/delete/<int:package_id>/', views.delete_package, name='delete_package'),
    path('package/', views.package_view, name='package'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset-password/<uidb64>/<token>/', views.reset_password, name='reset_password'),
    path('adminmain/', views.adminmain_view, name='adminmain_view'),
    path('delete_user/<int:reg_id>/', views.delete_user, name='delete_user'),
    path('review-users/', views.review_users, name='review_users'),
    path('blogs/create/', views.blog_create, name='blog_create'),
    path('blog/edit/<int:blog_id>/', views.edit_blog, name='edit_blog'),
    path('blog/delete/<int:blog_id>/', views.delete_blog, name='delete_blog'),
    path('create-notification/', views.create_notification, name='create_notification'),
    path('delete-notification/<int:notification_id>/', views.delete_notification, name='delete_notification'),
    path('logout/', views.logout, name='logout'),
    path('payment/<int:package_id>/', views.payment_page, name='payment_page'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('notifications/', views.view_notifications, name='view_notifications'),
    path('blogs/', views.blog_list, name='blog_list'),
    path('search_profiles/', views.search_profiles, name='search_profiles'),
    path('send-request/<int:personal_id>/', views.send_request, name='send_request'),
    path('view-sent-requests/', views.view_sent_requests, name='view_sent_requests'),
    path('received-requests/', views.view_received_requests, name='view_received_requests'),
    path('accept-request/<int:request_id>/', views.accept_request, name='accept_request'),
    path('reject-request/<int:request_id>/', views.reject_request, name='reject_request'),
    path('feedback/', views.submit_feedback, name='feedback'),
    path('view-feedback/', views.view_feedback, name='view_feedback'),
    path('match-preference/<int:reg_id>/', views.match_preference_view, name='match_preference'),
   

]
